* Hamster


Replace your mouse with your keyboard!

Main concept was inspired by [[mouseless][https://mouseless.click]].

** Install
*** NixOS
#+begin_src bash
  direnv allow
  cargo build --release
#+end_src
*** Other
Install required dependencies (see =shell.nix=), then =make=.

** Usage
The core of =hamster= is the deamon (=hamsterwheel=): it waits for commands sent to it. Once it runs, commands can be sent via:
- =hamstersend overlay=: cover the screen in a grid for moving the mouse
- =hamstersend scrollup=: scroll up
- =hamstersend scrolldown=: scroll down
- =hamstersend click N=: click mouse button N (1 <= N <= 5)

*** The Overlay
- Press =Esc= to close it
- Press the two keys corresponding to the cell to move the mouse to its center.
- Press =L= to lock the overlay (it won't go away after moving the mouse). Not that you cannot click through the overlay because mouse passsthrough apparently dosen't exist. This will make the selected cell, if any, recursively give more options for more cliking precision.

** Demo
TODO
